version: '3'

name: contenedor-docentes

services:
  db:
    image: oracle/database:21.3.0-ee
    container_name: docentes_db
    hostname: system
    environment:
      ORACLE_SID: DBDOC
      ORACLE_PDB: DBPDOC
      ORACLE_PWD: Espe.2023
      ORACLE_CHARACTERSET: AL32UTF8
      ORA_SDTZ: Ecuador
    ports:
      - "1522:1521"
    tty: true
    privileged: true
    networks:
      - proyecto-docente-network
    volumes:
      - oracle-data:/opt/oracle/oradata

  docente:
    image: microservicio-docente:1.1
    container_name: microservicio-docente
    ports:
      - "8084:8084"
    environment:      
      ORACLE_SID: DBDOC # Container database name
      ORACLE_PDB: DBPDOC # Pluggable database name
      ORACLE_PWD: Espe.2023
      ORACLE_CHARACTERSET: AL32UTF8
      ORA_SDTZ: Ecuador
    depends_on:
      - db
    networks:
      - proyecto-docente-network

networks:
  proyecto-docente-network:
    driver: bridge

volumes:
  oracle-data:
    driver: local
